// "Does this test cover this component?" — ONE definition, loaded by both
// runtimes.
//
// WHY THIS FILE EXISTS
// --------------------
// The honest-numbers contract (docs/measured-numbers.md) turns on one
// predicate: a number is measured only when a PASSED test DIRECTLY COVERS the
// subject. That predicate was written twice — `coverageOf()` in
// `server/lib/measured.js` and `coversDirectly()` in `web/js/measured.js` — and
// the two answered differently. The server treated "a step of the runbook the
// test executed names this component" as DIRECT; the browser file said, in its
// own words, that a component number needs the component named on the test
// itself, "never inferred from a shared runbook or a dependency closure".
//
// One contract with two implementations is a contract with a coin flip in it,
// and this one flipped the wrong way: the deployment-order generator tags
// nearly every component onto nearly every step, so linking that runbook to a
// single passed test marked the ENTIRE workspace — a DLQ, three S3 buckets, a
// secrets store — as `covers:"direct"`, `measured`, `verdict:met`.
//
// So the rule lives here, in `web/js/`, because that is the only directory both
// runtimes can load without a build step: the browser fetches it as a static
// module and Node imports it by relative path from `server/lib/measured.js`.
// No bundler, no duplicate, nothing to keep in sync.
//
// THE SEMANTICS, AND WHY
// ----------------------
// Evidence about a component is a claim someone made about THAT component:
//
//   * `test.componentId` / `test.componentIds[]` / `appTests[].componentId`
//     are written by the person who ran the test. They say "we exercised this
//     component and checked its success bar". That is an OBSERVATION, and it is
//     the only thing that can make a number measured.
//
//   * a runbook step's `componentIds[]` is AUTHORING METADATA about a
//     procedure. It says the step is about this component — not that the step
//     ran, not that it was checked, not that anyone looked at the component
//     afterwards. It is written once, by a generator, for every component in
//     the plan; a step can be skipped, gated out, or be a no-op; and nothing
//     anywhere records a per-step, per-component outcome. Breadth generated by
//     a machine is not evidence produced by a run.
//
// Hence a runbook step naming the component is real information but WEAKER
// evidence than an app test naming it, and it gets its own level,
// `runbook-step`, which is reported and never measured-eligible. It sits above
// `closure` (which is about the subject's NEIGHBOURS) because it is at least
// about the subject, and above `runbook` (the runbook is merely linked).
//
// The practical consequence, and the point of the change: a passed test that
// names ONE component measures THAT component. Everything else in the
// workspace stays unmeasured — which is a state, not a failure.
//
// Pure functions. No DOM, no fetch, no I/O, no throwing on malformed input.

/** Coverage levels, strongest first. Only 'direct' may produce a measurement. */
export const COVERAGE_LEVELS = Object.freeze(['direct', 'runbook-step', 'closure', 'runbook', 'none']);

/** The one measured-eligible level. Everything else is context, not evidence. */
export const MEASURED_ELIGIBLE = 'direct';

/** Human wording for a level, used wherever a UI has to explain a number. */
export const COVERAGE_NOTE = Object.freeze({
  direct: 'the test names this component itself',
  'runbook-step': 'a step of the runbook this test executed names this component — a procedure that touched it, '
    + 'not a measurement of it',
  closure: 'the test names something in this component\'s dependency closure, not the component',
  runbook: 'the test only shares a runbook with this component; no step names it',
  none: 'no relationship',
});

const arr = (v) => (Array.isArray(v) ? v : []);
const str = (v) => (v === null || v === undefined ? '' : String(v));

// Component ids the TEST ITSELF names. Accepts both shapes a test arrives in:
// the raw store record and the flattened object service.js builds.
function idsNamedByTest(t) {
  return [
    ...arr(t?.componentIds).map(str),
    ...(t?.componentId ? [str(t.componentId)] : []),
    ...arr(t?.appTests).map((a) => str(a?.componentId)),
  ].filter(Boolean);
}

/**
 * coverageOf(test, componentId, options) -> one of COVERAGE_LEVELS
 *
 * options:
 *   runbooks   — the runbooks collection, enables the 'runbook-step' level
 *   closureIds — Set/array of the subject's dependency-closure ids
 *
 * For the WORKSPACE subject (`componentId` null/empty) every test is 'direct':
 * a workspace-level RTA is a workspace-level claim.
 */
export function coverageOf(test, componentId, options = {}) {
  if (!componentId) return test ? 'direct' : 'none';
  if (!test || typeof test !== 'object') return 'none';
  const id = str(componentId);

  // 1. the test names it — the only measured-eligible answer.
  if (idsNamedByTest(test).includes(id)) return 'direct';

  // 2. a step of the runbook this test executed names it. Real, weaker, and
  //    deliberately NOT 'direct' (see the header).
  const runbookId = str(test.runbookId);
  let sharesRunbook = false;
  let namedByStep = false;
  if (runbookId) {
    for (const rb of arr(options.runbooks)) {
      if (str(rb?.id) !== runbookId) continue;
      sharesRunbook = true;
      const steps = [...arr(rb.steps), ...arr(rb.rollback)];
      if (steps.some((s) => arr(s?.componentIds).map(str).includes(id))) { namedByStep = true; break; }
    }
  }
  if (namedByStep) return 'runbook-step';

  // 3. the test names a NEIGHBOUR of the subject.
  const closure = options.closureIds instanceof Set
    ? options.closureIds
    : new Set(arr(options.closureIds).map(str));
  if (closure.size) {
    const named = idsNamedByTest(test);
    if (named.some((cid) => cid && cid !== id && closure.has(cid))) return 'closure';
  }

  if (sharesRunbook) return 'runbook';
  return 'none';
}

/** Shorthand for the measured-eligibility test itself. */
export function coversDirectly(test, componentId, options = {}) {
  return coverageOf(test, componentId, options) === MEASURED_ELIGIBLE;
}

export default coverageOf;
